# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    tmp.dir: 'var/tmp'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Command\Input\InputValidator:
        arguments:
            $tmpDir: '%tmp.dir%'

#    Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor: ~
#    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~
#
#    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
#        tags:
#            - 'serializer.normalizer'
#        arguments:
#            $nameConverter: '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
#            $propertyTypeExtractor: '@Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor'

